### ISSUE TITLE
Need help in windows

### ISSUE THREAD

**Issue by zhea55** [ukyouz/SublimeText-SimpleFuzzy#1] opened 2021-08-03 01:35 UTC
I use your plugin in windows.

which rg will be the problem.

Could you add a config to specify the rg.exe location?

**Comment by zhea55** [comment] 2021-08-03 02:11
simply replace which with where should be work.

But sublime not load the package, after i change the .sublime-package code.

**Comment by ukyouz** [comment] 2021-08-03 05:34
Adding your rg executable folder into Windows environment path may help!

**Comment by zhea55** [comment] 2021-08-03 05:41
Already tried，not working.

![WeCom Screenshot_20210803133925](https://user-images.githubusercontent.com/7816215/127963775-beb821d1-ac76-4d8d-aa72-d52833194634.png)



I think because which rg return empty string.

**Comment by ukyouz** [comment] 2021-08-03 11:51
okay, the problem is `which` command fails and I figure out that such checking condition is redundant so I will simply remove it at next update.

**Comment by ukyouz** [comment] 2021-08-03 13:58
This issue should be fixed in version 1.1.3, also I add a `simple_fuzzy_chk_cmd` options.

**Closed** 2021-08-03 13:57 UTC
